
security:
  jwt:
    secret-key: verysecretkeyohsosecretdamnhowlongisthispleasedontusethisinproduction
    token-duration: 1D

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mobile
    username: root
    password: 1234
  datasource.show-sql: true
  jpa.show-sql: true
  jpa:
    hibernate:
      ddl-auto: none
#      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  jta:
    atomikos:
      connectionfactory:
        borrow-connection-timeout: 30000
        ignore-session-transacted-flag: true
